---
title: "lab_7"
author: "Tian Walker, Dominik Grätz, Amber Somarriba, Brittany Spinner, Rachel Miller-Moudgil"
date: "2022-11-03"
output: pdf_document
bibliography: [references.bib]
---

# commit 1 (code)

```{r Commit 1 setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height=8, fig.width=6.5)
library(rio)
library(here)
library(tidyverse)

star <- import(here("data", "star.csv"))

```

# commit 3
```{r Commit 3}

#head(star)

star1 <- star %>% 
  group_by(sex, frl) %>% 
  summarize(math_mean = mean(tmathss),
math_sd = sd(tmathss),
rdg_mean = mean(treadss),
rdg_sd = sd(treadss)) 

knitr::kable(star1, booktabs = TRUE)
```


# commit 4
```{r Commit 4}
star$frl <- factor(star$frl)


ggplot(star, aes(x = totexp, y = tmathss)) +
  geom_point(color = "grey") + 
  geom_smooth(aes(color = frl), method = "lm")+
  labs(title = "Relation between teacher experience and math scores",
         subtitle = "Separate regression lines displayed by freereduces price lunch status",
         x = "Teacher Experience (years)",
         y = "Total Math Scale Score", 
       color = "Lunch status")+
  scale_color_discrete(breaks = c("yes", "no"), labels = c("yes" = "Free/Reduced Price Meals", "no" = "Paid Meals"))+
  #scale_color_discrete(breaks = c("yes", "no"))+
  theme_minimal() +
  theme(legend.position = "bottom")

#dominiks version
#test
```


\newpage
#References 

